FROM openjdk:22-jdk
WORKDIR /app
COPY target/*.jar app.jar

ENV COMMUNICATION_SERVICE_MONGO_URI=$COMMUNICATION_SERVICE_MONGO_URI
ENV COMMUNICATION_SERVICE_MONGO_DB=$COMMUNICATION_SERVICE_MONGO_DB
ENV STREAMING_URL=$STREAMING_URL
ENV RABBITMQ_HOST=$RABBITMQ_HOST
ENV RABBITMQ_PORT=$RABBITMQ_PORT
ENV RABBITMQ_USERNAME=$RABBITMQ_USERNAME
ENV RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
ENV RABBITMQ_VIRTUAL_HOST=$RABBITMQ_VIRTUAL_HOST
ENV RABBITMQ_SSL_ENABLED=$RABBITMQ_SSL_ENABLED

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]