apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service-deployment
  labels:
    app: communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
        - name: communication-service
          image: joeltompt/qorvia-communication-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: communication-service-secrets