apiVersion: v1
kind: Service
metadata:
  name: communication-service-service
spec:
  selector:
    app: communication-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
